Neos:
  Neos:
    Ui:
      resources:
        javascript:
          'Psmb.Footnote:Footnote':
            resource: resource://Psmb.Footnote/Public/JavaScript/Footnote/Plugin.js
    fusion:
      autoInclude:
        Psmb.Footnote: true